# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: zed windows build

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: '23 00 * * *'

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'

permissions:
  contents: read

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone zed repo
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          path: zed
      - name: patch zed
        run: |
          mv patchs zed/
          cd zed
          git reset --hard
          find patchs -type f -name "*.patch" -print0 | xargs -0 -I {} sh -c 'patch -p0 < "{}"'
      - name: upload patched source to artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-patched-source
          path: zed/
  build:
    needs: patch
    runs-on: windows-2022
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - amd64
          # - amd64_x86
          # - amd64_arm64
    permissions:
      contents: write
    steps:
      - name: Download patched source artifact
        uses: actions/download-artifact@v4
        with:
          name: zed-patched-source
          path: zed
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasi
      - name: setup rust cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          workspaces: |
            zed/
      - name: setup windows build tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          sdk: 10.0.20348.0
          # toolset: 14.11
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.0
        with:
          # You can set the Vulkan SDK version to download.
          # Defaults to latest version, if version not set.
          vulkan_version: 1.3.231.1
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
      - name: fixed long path
        shell: pwsh
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
      - name: build zed
        run: |
          git config --system core.longpaths true
          ls
          cd zed
          rustup target add wasm32-wasip1
          cargo build --release
      - name: upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: zed-${{ matrix.arch }}
          path: zed/target/release/zed.exe
        
  release:
    needs: build
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zed-amd64
          path: target/
      - name: set time
        run: |
          TIME="$(TZ='Asia/Shanghai' date +'%H:%M:%S')"
          DATE="$(TZ='Asia/Shanghai' date +'%Y-%m-%d')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
      - name: create release artifact
        run: zip -r zed-windows.zip target/*
      - name: release latest
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/auto-release')
        with:
          name: Nightly - latest - ${{ env.DATE }}
          tag_name: amd64-win
          prerelease: true
          make_latest: true
          files: |
            target/zed.exe
      # - name: release
      #   uses: softprops/action-gh-release@v2
      #   # if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/auto-release')
      #   with:
      #     name: Nightly ${{ env.DATE }}
      #     tag_name: "nightly_${{ env.DATE }}"
      #     files: |
      #       target/zed.exe

          
